"""empty message

Revision ID: beae618e7ffd
Revises: 1af9cef823ce
Create Date: 2020-05-16 16:37:40.175860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beae618e7ffd'
down_revision = '1af9cef823ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=200), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
